AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: User service

Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 25
  Api:
    OpenApiVersion: '3.0.1'

Resources:
  UserRegisterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleUserRegister
  StudendESIndexLambda:
    Type: AWS::Serverless::Function
    Policies: dynamoDB-es
    Properties:
      CodeUri: user_deploy.jar
      Hanlder: com.online_education.user.server.UserServiceHandler::indexStudent
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:us-east-1:343484209947:table/student/stream/2020-12-30T22:46:15.048
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            Enabled: true