AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: User service

Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 25
  Api:
    OpenApiVersion: '3.0.1'

Resources:
  UserRegisterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleUserRegister
  UserCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleUserCreate
      Policies:
        - DynamoDBCrudPolicy:
            TableName: student
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /student
            Method: POST
  UserUpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleUserUpdate
      Policies:
        - DynamoDBCrudPolicy:
            TableName: student
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /student
            Method: PATCH
  UserGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleUserGet
      Policies:
        - DynamoDBReadPolicy:
            TableName: student
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /student
            Method: GET

  StudendESIndexLambda:
    Type: AWS::Serverless::Function
    Policies: dynamoDB-es
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::indexStudent
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:us-east-1:343484209947:table/student/stream/2020-12-30T22:46:15.048
            StartingPosition: LATEST
            BatchSize: 100
            Enabled: true

  TeacherCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleTeacherCreate
      Policies:
        - DynamoDBCrudPolicy:
            TableName: teacher
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /teacher
            Method: POST
  TeacherUpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleTeacherUpdate
      Policies:
        - DynamoDBCrudPolicy:
            TableName: teacher
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /teacher
            Method: PATCH
  TeacherGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_deploy.jar
      Handler: com.online_education.user.server.UserServiceHandler::handleTeacherGet
      Policies:
        - DynamoDBReadPolicy:
            TableName: teacher
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /teacher
            Method: GET
