AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: sample service

Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 25
  Api:
    OpenApiVersion: '3.0.1'

Resources:
  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ${servicename}_deploy.jar
      Handler: com.online_education.${servicename}.server.${ServiceName}ServiceHandler::handleHelloWorld
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /hello
            Method: GET