# This is a basic workflow to help you get started with Actions

name: Create New Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'servicename (ep. helloworld)'
        required: true
      service_class_name:
        description: 'Service Name (ep. HelloWorld)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: envsubst
        uses: foxted/github-action-envsubst@v1.0.2
      - name: test
        run: |
          ls
          export service_name='${{ github.event.inputs.service_name }}'
          echo $service_name

      
