# This is a basic workflow to help you get started with Actions

name: Create New Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      SERVICE_NAME:
        description: 'Service name (ep. helloworld)'
        required: true
      SERVICE_CLASS_NAME:
        description: 'Service class name (ep. HelloWorld)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.SERVICE_NAME }}
      SERVICE_CLASS_NAME: ${{ github.event.inputs.SERVICE_CLASS_NAME }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: envsubst
        uses: foxted/github-action-envsubst@v1.0.2
      - name: create new service package
        run: |
          export SERVICE_NAME=$SERVICE_NAME 
          envsubst < lambda_template/BUILD > $SERVICE_NAME/BUILD
          cat $SERVICE_NAME/BUILD
      
