# This is a basic workflow to help you get started with Actions

name: Create New Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      SERVICE_NAME:
        description: 'Service name (ep. helloworld)'
        required: true
      SERVICE_CLASS_NAME:
        description: 'Service class name (ep. HelloWorld)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.SERVICE_NAME }}
      SERVICE_CLASS_NAME: ${{ github.event.inputs.SERVICE_CLASS_NAME }} 
      JAVA_PACKAGE_PATH: src/main/java/com/online_education
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: envsubst
        uses: foxted/github-action-envsubst@v1.0.2
      - name: create new service package
        run: |
          mkdir $JAVA_PACKAGE_PATH/$SERVICE_NAME
          mkdir $JAVA_PACKAGE_PATH/$SERVICE_NAME/command
          mkdir $JAVA_PACKAGE_PATH/$SERVICE_NAME/server
          export SERVICE_NAME=$SERVICE_NAME 
          export SERVICE_CLASS_NAME=$SERVICE_CLASS_NAME
          envsubst < lambda_template/BUILD > $JAVA_PACKAGE_PATH/$SERVICE_NAME/BUILD
          envsubst < lambda_template/template.yaml > $JAVA_PACKAGE_PATH/$SERVICE_NAME/template.yaml
          envsubst < lambda_template/command/HelloWorldCommand.java > $JAVA_PACKAGE_PATH/$SERVICE_NAME/command/HelloWorldCommand.java
          envsubst < lambda_template/server/Component.java > $JAVA_PACKAGE_PATH/$SERVICE_NAME/server/Component.java
          envsubst < lambda_template/server/ServiceHandler.java > $JAVA_PACKAGE_PATH/$SERVICE_NAME/server/ServiceHandler.java
      - name: commit changes
        run: |
          git branch --set-upstream-to master origin/master
          git checkout -b ${{ github.actor }}/create-$SERVICE_NAME-service
          git config --local user.name ${{ github.actor }}
          git add . 
          git commit -m "Create new service: $SERVICE_NAME"
          git push
          
