# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow
name: Deploy
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name'
        required: true
        default: 'weather'
      branch:
        description: 'Branch name'
        required: true
        default: 'master'
jobs:
  deploy:
    env:
      JAVA_PACKAGE_PATH: src/main/java/com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }} 
      - name: Install bazel
        uses: ngalaiko/bazel-action/1.2.1@master
      - name: Build deploy jar
        run: bazel build //$JAVA_PACKAGE_PATH/${{ github.event.inputs.service }}:${{ github.event.inputs.service }}_deploy.jar
      - name: Copy binary
        run: |
          cp bazel-bin///$JAVA_PACKAGE_PATH/${{ github.event.inputs.service }}/${{ github.event.inputs.service }}_deploy.jar $JAVA_PACKAGE_PATH/${{ github.event.inputs.service }}
          cd $JAVA_PACKAGE_PATH/$SERVICE
          ls
      - name: AWS SAM CLI setup
        uses: tkt-actions/aws-sam-cli@v1.0.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-esat-1
        with:
          cmd: sam deploy --s3-bucket staging-sam-lambda-deploy --stack-name api-stack --capabilities CAPABILITY_IAM --template-file $JAVA_PACKAGE_PATH/${{ github.event.inputs.service }}/template.yaml
