# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow
name: Deploy
env:
  JAVA_PACKAGE_PATH: src/main/java/com
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name'
        required: true
        default: 'weather'
      branch:
        description: 'Branch name'
        required: true
        default: 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }} 
      - name: Install bazel
        uses: ngalaiko/bazel-action/1.2.1@master
      - name: Build deploy jar
        run: bazel build //$JAVA_PACKAGE_PATH/${{ github.event.inputs.service }}:${{ github.event.inputs.service }}_deploy.jar
      # https://github.com/r0zar/sam-deploy-action
      - name: Deploy
        uses: r0zar/sam-deploy-action@v1.0
        env:
          TEMPLATE: $JAVA_PACKAGE_PATH/template.yaml
          AWS_STACK_NAME: ${{ github.event.inputs.service }}-staging
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: 'staging-sam-lambda-deploy'      
