name: CI
on: [push]
env:
  JAVA_PACKAGE_PATH: src/main/java/com/online_education
  JAVA_TEST_PATH: src/test/java/com/online_education
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.7.2
    - name: Build service
      run:  bazel build //$JAVA_PACKAGE_PATH/...
    - name: Test
      run:  bazel test //$JAVA_TEST_PATH/...
