name: CI
on: [push, pull_request]
env:
  JAVA_PACKAGE_PATH: src/main/java/com/online_education
  JAVA_TEST_PATH: src/test/java/com/online_education
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bazel
      uses: ngalaiko/bazel-action/1.2.1@master
    - name: Build service
      run:  bazel build //$JAVA_PACKAGE_PATH/...
    - name: Test
      run:  bazel test //$JAVA_TEST_PATH/...
