name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bazel
      uses: ngalaiko/bazel-action/1.2.1@master
    - name: Build weather
      run: bazel build src/main/java/com/weather:weather_deploy.jar
